### PR TITLE
support for deleting request & response headers

### PR DESCRIPTION
**Pull request by leostarcevic**
DFP should have support for deleting request & response headers just like they can be added/changed.

### CODE REVIEW

**Comment by vfarcic** [comment]
Can you describe a scenario where this would be useful?

When services are managed through Swarm Listener, it should not matter whether there is the option to remove a header. Every time a service is created or updated, new proxy config is created. If a service is created with a header defined as a label, the proxy will have it in its config. Later on, if that label is removed, it'll be removed from the proxy as well. Even if services are added manually, it would be enough to send another request without the header and it would be removed from the proxy.

**Comment by leostarcevic** [comment]
Scenario:
What if I want to remove headers from someone else's service making requests through my dfp, where I don't want that service's headers to reach my application.

I might not have a great scenario myself yet but isn't it also weird that we can add/set headers but not remove them? after all it's a haproxy feature that would be nice to include since dfp is based on it?

**Comment by vfarcic** [comment]
How about implementing it in a more general way that would apply to any element of the config? Maybe a new endpoint `/v1/docker-flow-proxy/removeParam` that would support removal of any of the paramers (e.g. `params= addReqHeader,connectionMode, serviceDomain `)? When receiving a request, proxy would remove those params from its data and recreate the config. If we add the option to remove one individual parameter, tomorrow we'll have similar requests for others. If it's generic, it would provide consistency and, at the same time, reduce development time.

What do you think?

**Comment by vfarcic** [comment]
Ignore my previous comment! I missunderstood this PR.

**Comment by vfarcic** [comment]
Now I get it :)

This PR is great! There is a conflict with one of the commits I pushed earlier today. If you can merge with the master and submit a new PR, I'll approve it right away.

P.S. Sorry for the confusion I made with my missplaced comments.

**Comment by leostarcevic** [comment]
No problem, I'm glad my scenario made sense and I appreciate discussions about PR's before merging them 👍 

I'll fix the merge conflict asap!
btw. I hope all my "issues/feature requests/pr's" are ok, they'll keep coming until I can move all existing haproxy configs to dfp ;)

**Comment by vfarcic** [comment]
Just keep the PRs coming :)

**Pull request merged**
