### PR TITLE
Added support for external outbound hostname in the proxy config.

### PR DESCRIPTION
**Pull request by highfestiva**
The outbound hostname feature is useful when the proxy is not part of the
swarm. In a large corporate network setting, swarms may be regularly
decommissioned and re-created, but external parts integrating with the
swarms can not be reconfigured. (Updating DNS records is often times out
of the question for policy and/or bureaucracy reasons.)

### CODE REVIEW

**Comment by vfarcic** [comment]
Thanks for the pull request. I'll go through it soon and let you know if there's anything to be modified.

**Comment by vfarcic** [comment]
I had a look at your code. My understanding is that you're replacing serviceName with outboundHostname. Maybe a more elegant solution would be to specify a hostname as serviceName. That way there would be no need to introduce one more parameter. The only change would be in the swarm-listener to use a serviceName label instead of the "real" name of the service.

What do you think?

**Comment by highfestiva** [comment]
Hi Viktor,

The problem with that is when you have multiple instances (with different
config) running in the same swarm. In my current case, we're using eight
instances (!) of each application to cover for an old legacy system, but
even for a more "sensible" setup you might want one instance for system
tests, one for integration tests and one for production. What do you think?
:]

Kind regards,
Jonas


2016-12-11 23:13 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
You're right. The solution you proposed is the correct one.

I made some changes in the meantime that result in a few conflicts. Can you merge your code with the master branch, resolve conflicts, and submit a new pull request? Everything looks correct so I'll merge it as soon as conflicts are resolved.

**Comment by vfarcic** [comment]
Thank you

**Comment by highfestiva** [comment]
Thank you! As I understand it, this feature is now included
in vfarcic/docker-flow-proxy:latest?

Kind regards,
Jonas

2016-12-14 0:45 GMT+01:00 Viktor Farcic <notifications@github.com>:

**Comment by vfarcic** [comment]
Yes it is. I'm a huge fan of continuous deployment. Every commit is built
and released. In this case, the only thing missing is to make it an
"official" release. I was planning to do that tomorrow. Maybe you can help
me out by writing a short description of the feature/release?

**Comment by vfarcic** [comment]
It's part of the release [1.121](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.121 )

**Comment by highfestiva** [comment]
Hi again Viktor,

Sorry for the late reply. If you still need a description this is from 
my original commit message - it's acceptable.

Support for external (outbound) hostname in the proxy config.

The outbound hostname feature is useful when the proxy is not part of 
the swarm. In a large corporate network setting, swarms may be regularly 
decommissioned and re-created, but external parts integrating with the 
swarms can not be reconfigured. (Updating DNS records is often times out 
of the question for policy and/or bureaucracy reasons.)

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "Viktor Farcic" <notifications@github.com>
Till: "vfarcic/docker-flow-proxy" <docker-flow-proxy@noreply.github.com>
Kopia: "Jonas Byström" <highfestiva@gmail.com>; "Author" 
<author@noreply.github.com>
Skickat: 2016-12-14 19:14:03
Ämne: Re: [vfarcic/docker-flow-proxy] Added support for external 
outbound hostname in the proxy config. (#79)

**Comment by vfarcic** [comment]
Thanks!

I added it to the [release 1.121](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.121)

**Pull request merged**
