### PR TITLE
arm and amd64 Dockerfiles

### PR DESCRIPTION
**Pull request by RaymondMouthaan**
Added arm and amd64 Dockerfiles to build docker flow proxy images for these architectures. 
Also a .travis.yml added using qemu and manifest-tool to build for arm and amd64.

### CODE REVIEW

**Review by vfarcic — CHANGES_REQUESTED** [review]
I tried it out in EC2 instances that are created on each build and it works like a charm :)

I made a few notes below so that we have a clean PR only with the things we'll need.

**Comment by vfarcic** [comment]
Merged. I'll let you know once it's added to Jenkinsfile (and is working).

**Comment by vfarcic** [comment]
It's finished. From now on, each commit that passes all the tests will push two ARM images (`latest-arm` and `[RELEASE_NUMBER]-arm`. Can you please try `latest-arm` and let me know whether it works as expected?

**Comment by RaymondMouthaan** [comment]
Haii Viktor,
Very nice you merged and added arm support to this project, happy to hear that! Thank you! 

I've tested the image using the docker run command like this:

```
docker run -it --name dfp vfarcic/docker-flow-proxy:latest-arm
```

Which starts the container nicely with these log lines:

```
2018/04/01 08:15:44 Starting HAProxy
2018/04/01 08:15:44 Starting "Docker Flow: Proxy"
```

I also tested the image using the docker stack command:
```
docker stack deploy -c docker-compose-docker-flow.yml proxy
``` 

where the compose file looks like this:

```
version: "3"
services:
  proxy:
    image: vfarcic/docker-flow-proxy:latest-arm
    ports:
      - 90:80
      - 9443:443
      - 6379:6379
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - STATS_USER=my-user
      - STATS_PASS=my-pass
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == docker1]
networks:
  proxy:
    external: true
```
Unfortunately (but I more or less was expecting that) gives an error like this:
```
no suitable node (scheduling constraints not satisfied on 4 nodes; unsupported platform on 1 node)
``` 

I faced this error several times and there are two solutions to this. The first one is easiest, but not the nicest (it's more or less a workaround). By adding **--resolve-image never** (see [Docker Stack Deploy](https://docs.docker.com/engine/reference/commandline/stack_deploy/)) to the docker stack command, the registry is not being queried to resolve image digest and supported platforms.

So the full command  (which works) looks like this:
```
docker stack deploy --resolve-image never -c docker-compose-docker-flow.yml proxy
```

However a nicer and better solution would be to use the manifest tool created by Phil Estes. This tool creates a manifest list to support multi architectures (see [this blog](https://blog.docker.com/2017/11/multi-arch-all-the-things/) for more details). Using this tool it's not even needed to explicitly specify define the architecture while deploying and image. For example currently docker flow proxy gets deployed like:

```
# for arm
docker run -it --name dfp_arm vfarcic/docker-flow-proxy:latest-arm
# for x86_64
docker run -it --name dfp_x86_64 vfarcic/docker-flow-proxy:latest
```

but when using a manifest list the command would be:

```
docker run -it --name dfp vfarcic/docker-flow-proxy:latest
```

Using the manifest list, it automatically detects which image is needed for which architecture. This is a nice advantage, because a one doesn't need to worry about the architecture.
Also it solves the '--resolve-image never' argument and it gives a nice overview of the tags supported by the image. Currently 2 but could be easily extended to more.

screen shot 2018-04-01 at 11 09 05

Below a snippet from one of my .travis.yml files:

```
...
# Download manifest-tool
      wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64
      mv manifest-tool-linux-amd64 manifest-tool
      chmod +x manifest-tool
      # Push manifest-list
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template "raymondmm/sonweb:${TRAVIS_TAG}-OS-ARCH" --target "raymondmm/sonweb:$TRAVIS_TAG"
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template "raymondmm/sonweb:${TRAVIS_TAG}-OS-ARCH" --target "raymondmm/sonweb:latest"
```

This section of the yml, downloads the tool, creates the manifest list and pushes it to docker hub for the images build in previous steps.

Apologisies for the long post, but I hope you consider using the manifest tool within your Jenkins process.

**Comment by vfarcic** [comment]
Apologies in advance if I misunderstood. I never used ARM...

If we execute `manifest-tool` and push it to Docker Hub, Docker will recognize the architecture and we'll be able to use `latest` no matter whether it's Linux or ARM. If that's the case, it sounds great.

Can you send a PR with changes to https://github.com/vfarcic/jenkins-shared-libraries/blob/master/vars/dfReleaseArm.groovy? That function is executed whenever a commit is made to DFP master branch. It's Jenkins syntax but you'll see that it's simply a list of `sh` commands.

**Comment by vfarcic** [comment]
Can you please test that the latest release works as expected?

**Pull request merged**
