### PR TITLE
#fixes-issue-165

### PR DESCRIPTION
**Pull request by s4s0l**
details:
* calling get-services from swarm-listener on start, until succeeds
* Refactorings:
** service creation code moved to proxy package as it would cause cyclic dependency with actions package
** global reload/refresh operations moved to Reload action

### CODE REVIEW

**Comment by s4s0l** [comment]
Sorry for quite massive changes but I had trouble understanding how some things work. Service creation stuff had to be changed and it is one of the reasons every second file was modified. Other reason was I tried to do some refactoring, as 'class' Reconfigure had already too big responsibility and quite clumsy interface:
* there was (and still is unfortunately) cyclic dependency between Reload and Reconfigure
* Reconfigure has an interface that suggest it operates on one service, but in Reconfigurable interface there are methods that operate on all services

Most of the changes come from slight modifications of these interfaces. As they are heavily mocked in tests it ended up with me needing to modify some details here and there. Because what I was trying to achieve is not complete, so I believe there is a need for description of my 'vision'.

New method 'ReloadConfig' had to be placed somewhere, and because Reconfigure seems to be the place to manipulate one service i decided to put it in Reload. That seemed like a good idea so i moved swarm-listener logic from ReloadServicesFromListener to Reload interface. This way all swarm-related things are kept together. In Reload there was a method Execute(recreate bool, listenerAddr string) which was called with empty second argument in some places Even when the proxy was working with listener. I found it Very confusing, because it was actually doing 2 totally different things depending on that parameter. So I cleaned it up a bit. I failed when wanted to move method ReloadServicesFromRegistry to Reload (as It also operates on all services) but I kinda failed, as its quite merged with Reconfigure methods. 

What I don't like now is that Reload action and Reconfigure have large interfaces, while there should be one method only. There should be no cyclic dependencies between Reload and Reconfigure. I think there should be new action FetchConfiguration that would encapsulate swarm/consul configuration fetching. If it makes sense I'm willing to proceed, otherwise I can revert my changes and place new behavior into Reconfigure action and leave everything intact.

**Comment by s4s0l** [comment]
About failing travis - on my desktop it does not fail:) Seriously I don't know whats failing there.

**Comment by s4s0l** [comment]
Last thing: after my fixes DFP needs latest DFSL version, and then there is some side effect of this. When both DFP and DFSL start in the same time, proxy is reconfigured multiple times - first because of DFP fetching config from DFSL, and then subsequent calls from DFSL. I do not know if it can be avoided but can be minimized if DFSL was sending initial configuration as a json containing all services, not one by one.

**Comment by s4s0l** [comment]
So now there is new 'Action' Fetch that agregates all configuration fetches from consul or swarm, in different flavors. Problems left to resolve:
* Mocks are copied to few places
* What reload endpoint of DFP suppose to do - shouldnt it fetch config from consul? In swarm it used to initiate reconfiguration of whole cluster while in consul mode it just reloaded proxy as far as I understand what was going on...
* It would be nice to have 2 sets of actions one for consul second for swarm as there is a lot of ifelfizm inside actions + some action registry to look them up properly

But these kind of refactorings I'd leave for another PR. This one is bloated anyway. Sorry for that, but when I started I couldn't help myself. If your sense of clean code is not parallel to mine I have nothing against reverting all but reconfiguration feature.

**Comment by vfarcic** [comment]
> What I don't like now is that Reload action and Reconfigure have large interfaces, while there should be one method only. There should be no cyclic dependencies between Reload and Reconfigure. I think there should be new action FetchConfiguration that would encapsulate swarm/consul configuration fetching. If it makes sense I'm willing to proceed, otherwise I can revert my changes and place new behavior into Reconfigure action and leave everything intact.

Parts of the code are a mess. I started with one idea, moved to another, and so on. I'm doing my best to clean things up and garbage accumulates and initial design decisions that are now obsolete are haunting me.

I decided to sunset Consul so a part of this problem will disappear. I removed it from docs yesterday. I'll leave the code for a while longer to give people time to transition. I don't think there are many (if any) using Consul with DFP but I'd still like to maintain backwards compatibility for a while longer.

**Comment by vfarcic** [comment]
> About failing travis - on my desktop it does not fail:) Seriously I don't know whats failing there.

Travis uses env. variables used for  that are not available in PRs (otherwise anyone could push to my Hub account). I made a change to .travis so that push is not done on PRs. It'll be available once I merge it with this PR.

**Comment by vfarcic** [comment]
> Mocks are copied to few places

I think that's OK. It makes mocks code duplicated but the alternative would be to add mocks to non-tests and shipping it with the binary.

> What reload endpoint of DFP suppose to do - shouldnt it fetch config from consul? In swarm it used to initiate reconfiguration of whole cluster while in consul mode it just reloaded proxy as far as I understand what was going on...

Don't worry much about Consul. I consider it deprecated and it will be removed soon. It is a relic from before Docker 1.12.

> It would be nice to have 2 sets of actions one for consul second for swarm as there is a lot of ifelfizm inside actions + some action registry to look them up properly

Consul will be removed :)

**Comment by vfarcic** [comment]
Merged :)

I noticed only one problem. Swarm Listener is throwing "http: multiple response.WriteHeader calls" error. I'm not sure whether it is caused in the DFSL or DFP. Can you check it out?

**Pull request merged**
