### PR TITLE
Rewrite/replace the request that gets sent to the backend

### PR DESCRIPTION
**Pull request by f-minzoni**
I need to use HAProxy as a transparent proxy and I have a problem with the generated configuration. Basically, it seems to me that it doesn't manage the URLs under the specified path. So, I am trying to rewrite/replace the request that gets sent to the backend, adding a "reqrep" rule to the related config.
I have simplified the test scenario with a single ServicePath, that's what I need by now...

### CODE REVIEW

**Comment by vfarcic** [comment]
I'm not sure that adding reqrep rule for everyone would be a good idea. Many might not want it and even those that do might use different expressions.

I'd suggest we add it as a conditional. We can, for example, add a new query argument *reqrep*. If the argument is present, it's value would be added to the config. An example would be:

```bash
curl "$PROXY_IP:8080/v1/docker-flow-proxy/reconfigure?serviceName=books-ms&servicePath=/api/v1/books&reqrep=REQREP_VALUE"
```

I think that the major drawback is that REQREP_VALUE would need to be URL encoded and that might be tricky with RegEx.

What do you think? Would that fit your use case?

**Comment by f-minzoni** [comment]
Yes, your solution would be great. I hope to work on that soon. Thanks

**Comment by vfarcic** [comment]
Actually, I already implemented it. You can see the changes in the commit [c99055f280df70d2b68001a783e7c09fb10e72a1](https://github.com/vfarcic/docker-flow-proxy/commit/c99055f280df70d2b68001a783e7c09fb10e72a1). There is a new query param *pathType* that works together with *servicePath*. You can find more info in [Usage: Reconfigure](https://github.com/vfarcic/docker-flow-proxy#reconfigure) section. Would you mind trying it out?

Please let me know if you'd like to contribute. I have a backlog in Trello with nice-to-have features (mostly for the parent project Docker Flow).

**Comment by vfarcic** [comment]
Done in a separate commit

**Pull request closed without merging**
