### PR TITLE
Added new feature to reconfigure using real file templates

### PR DESCRIPTION
**Pull request by Xustyx**
Now you can use dynamic file or you can feel free to use static ones.

Examples of dynamic file templates:
portainer-fe.tmpl
```
    mode    http
    option  http-keep-alive
    acl domain_{{.ServiceName}} hdr_dom(host){{range .ServiceDomain}} -i {{.}}{{end}}
    acl url_{{.ServiceName}}{{range .ServicePath}} path_beg {{.}}{{end}}
    use_backend {{.ServiceName}}-be if url_{{.ServiceName}} domain_{{.ServiceName}}
```

portainer-be.tmpl
```
backend {{.ServiceName}}-be
    mode http
    option  forwardfor
    option  http-keep-alive
    server {{.ServiceName}} {{.ServiceName}}:{{.Port}}
```

There's a better code solution for this feature but requires rewrite the test and I'm not enought skilled with test in go.

Cheers!

### CODE REVIEW

**Comment by vfarcic** [comment]
Thanks for the pull request. I'll go through it in a day or two and get back to you.

**Comment by vfarcic** [comment]
The only problem with your code (as far as I could see) is that it tries to use Consul template parameters for Swarm services. The issue is that Consul uses the same templating as what the proxy uses for Swarm services (Go HTML template) and might easily produce undesired effects if a struct name coincides. Or maybe it wouldn't... Applying the same templating to both cases would require quite a lot of tests. It should not be a problem to do that if there would not be a plan to sunset Consul once everyone adopts Swarm. If I carry on the plan, investment in those tests would be useless. Also, `consulTemplateFePath` and `consulTemplateBePath` parameters are misleading if applied to non-Consul cases.

Can you look at the commit https://github.com/vfarcic/docker-flow-proxy/commit/d01d46b874de174bd379876f004d4ba9ca5378f8 and let me know what you think? I think it follows the same idea as what you did, except that it introduced two new parameters (`templateFePath` and `templateBePath`). I used the opportunity to add tests for the new cases.

P.S. I hope you're OK with me using your code without merging the pull request.

**Comment by Xustyx** [comment]
Hi,
Yes your commit it's better and do the same feature :) 
Thanks!

**Comment by vfarcic** [comment]
Closing in favour of https://github.com/vfarcic/docker-flow-proxy/commit/d01d46b874de174bd379876f004d4ba9ca5378f8 .

**Comment by vfarcic** [comment]
It's part of the release [1.121](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.121 )

**Comment by Xustyx** [comment]
ping @vfarcic

I have an issue with the new templates. 
When I use the new labels TemplateBePath and TemplateFePath like this
```
--label com.df.templateBePath=/templates/portainer/portainer-be.tpl
--label com.df.templateFePath=/templates/portainer/portainer-fe.tpl
```
with this content
```
#FE
    option http-keep-alive
    acl url_{{.ServiceName}}{{range .ServiceDest}}{{range .ServicePath}} path_beg {{.}}{{end}}{{end}}
    acl domain_{{.ServiceName}} hdr_dom(host) -i {{range .ServiceDomain}}{{.}} {{end}}
    use_backend {{.ServiceName}}-be if url_{{.ServiceName}} domain_{{.ServiceName}}

#BE
backend {{.ServiceName}}-be
    option forwardfor
    option http-keep-alive
    server {{.ServiceName}} {{.ServiceName}}:{{range .ServiceDest}}{{.Port}}{{end}}
```
 I get the next config:
```sh
    acl url_manager9000 path_beg /
    acl domain_manager hdr_dom(host) -i manager.swarme.net
    use_backend manager-be9000 if url_manager9000 domain_manager

    option http-keep-alive
    acl url_manager path_beg /
    acl domain_manager hdr_dom(host) -i manager.swarme.net
    use_backend manager-be if url_manager domain_manager

backend manager-be
    option forwardfor
    option http-keep-alive
    server manager manager:9000
```

If I'm using templates, why the proxy continues generating the default FE config "manager9000"?

**Comment by vfarcic** [comment]
What is the name of the service and port is exposes? If `ServiceName` is `manager` and `ServiceDest` is 9000, the config looks correct.

Can you write what would be the desired config from those templates?

**Comment by Xustyx** [comment]
Hi,

I want to add "option http-keep-alive" before FE acl's and "option forwardfor" "option http-keep-alive" before BE server.

Anyways, I don't understand why if I'm using the FE template label, the default config still existing.

**Comment by vfarcic** [comment]
Sorry for that. I misunderstood the problem. Let me check it out and get back to you with a fix.

**Comment by vfarcic** [comment]
@Xustyx Can you try the latest release and let me know if the "extra" frontend dissapeared?

**Comment by Xustyx** [comment]
Works fine now !!! Thanks :1st_place_medal:

**Pull request closed without merging**
