### PR TITLE
Fix issue with SNI routing when service exposes more than one destination port. 

### PR DESCRIPTION
**Pull request by faisyl**
The initial implementation was broken for multiple destination ports for a service. This fixes it.

### CODE REVIEW

**Comment by vfarcic** [comment]
It would be great if you could provide some instructions that I could use to create integration tests. If you don't have anything at hand, I can figure it out as well.

The same goes for tutorial. Do you think you could write something. It doesn't have to be a full blown text.

**Comment by faisyl** [comment]
I shall add some examples and stuff to this PR or the issue. I'm hoping to write a blog article on using docker-flow-proxy and SNI routing. If you can wait for a couple weeks - you can use some of that for the documentation. Otherwise I'll write something up soon.

**Comment by vfarcic** [comment]
There's no hurry with docs/article.

**Comment by faisyl** [comment]
For integration tests, 

Here's the brief of how we use SNI-routing and docker-flow-proxy:

1. We use wildcard certificates for our test domain. Assume it's *.test.com
2. We also have programatic access to a DNS server for test.com
3. As many folks can launch as many instances of their apps as they need - so long as the names don't clash. So user1 might pick app1-user1.test.com as their "top level app domain".  As long as there's no '.' in the name the wildcard cert will be valid for the certificate.
4. Each service lunched into the swarm gets one or more service name prepended to the app FQDN. For example my "auth" service would map to auth-app1-user1.test.com. DB might be db-app1-user1.test.com. 
5. Each time a service is mapped into swarm, the FQDN for the service is added to the DNS - pointing to one or more of the nodes running the proxy.

Services definitions look like this:

A service listening on 3 ports and all mapped to 443 on the proxy.
```
-- snip --
  master:
    image: registry.test.com/master:TAG1 
    deploy:
      replicas: 1
      labels:
        com.df.notify: 'true'
        com.df.distribute: 'true'
        com.df.pathType: "req_ssl_sni -i -m beg"
        com.df.servicePath.1: "auth-app1-user1."
        com.df.srcPort.1: 443
        com.df.reqMode.1: sni
        com.df.port.1: 6078
        com.df.servicePath.2: "sync-app1-user1."
        com.df.srcPort.2: 443
        com.df.reqMode.2: sni
        com.df.port.2: 5050
        com.df.servicePath.3: "web-app1-user1."
        com.df.srcPort.3: 443
        com.df.port.3: 6077
        com.df.reqMode.3: sni
        com.df.capacity: 1
        com.df.stype: sync
        dns.labels: ". auth sync web"
    environment:
-- snip --

```
Another service that maps 443 to 443 - but this time using a regular expression for SNI mapping. 
```
-- snip --
  node:
    image: registry.test.com/node:TAG1
    deploy:
      replicas: 1
      labels:
        com.df.notify: 'true'
        com.df.distribute: 'true'
        com.df.pathType: "req_ssl_sni -i -m reg"
        com.df.servicePath: "^(upload|restore)-app1-user1.*"
        com.df.srcPort: 443
        com.df.reqMode: sni
        com.df.port: 443
        com.df.capacity: 10
        com.df.stype: sync
        dns.labels: "upload restore"
    environment:
-- snip --

```
In my implementation, I'm using dns.labels to populate the DNS entries for the service endpoints. I'm using SSL certs from swarm secrets and HA-Proxy only acts as a router. The communication is end-to-end secured between the client and the end-service within the container. 

To add integration tests, something simple should suffice. The only problem will be wild-card certs or something like letsencrypt to issue individual certificates to backend services. Not sure how that can be achieved.

**Comment by vfarcic** [comment]
Wildcard certs will complicate integration tests. For now, I'll leave this feature untested on the higher level and rely on unit tests and trust your manual checks.

**Comment by vfarcic** [comment]
It's merged to the master and released as 1.396. Can you please do another round of manual tests to confirm everything works as expected?

**Comment by faisyl** [comment]
Tested against 1.396. Looks good. Thanks!

**Pull request merged**
